version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    user: root
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: phongthinh799/smeecotech2a:new
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.pem
    volumes:
      - /etc/letsencrypt/live/bemodernestate.site/fullchain.pem:/https/fullchain.pem:ro
      - /etc/letsencrypt/live/bemodernestate.site/privkey.pem:/https/privkey.pem:ro
    user: root
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
