// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SME_Ecotech2A.Infrastructure.Persistence;

#nullable disable

namespace SME_Ecotech2A.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260403034641_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugAttachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BugId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("BugId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("BugAttachments");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugRCAHistory", b =>
                {
                    b.Property<Guid>("RcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BugId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("OccurrenceNo")
                        .HasColumnType("int");

                    b.Property<string>("PreventionAction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RootCauseNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RootCauseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("RcaId");

                    b.HasIndex("BugId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("BugRcaHistories");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugTicket", b =>
                {
                    b.Property<Guid>("BugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BugCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("ImpactTimeline")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RcaRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RepeatedCount")
                        .HasColumnType("int");

                    b.Property<bool>("RepeatedFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RootCauseType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StepsToReproduce")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("VerifyBy")
                        .HasColumnType("char(36)");

                    b.HasKey("BugId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TaskId");

                    b.HasIndex("VerifyBy");

                    b.ToTable("BugTickets");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Industry")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ClientContact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ContactId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ConflictEvent", b =>
                {
                    b.Property<Guid>("ConflictEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConflictNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DaysImpacted")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FromProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ConflictEventId");

                    b.HasIndex("FromProjectId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("ConflictEvents");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ManagerID")
                        .HasColumnType("char(36)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ManagerID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Holiday", b =>
                {
                    b.Property<Guid>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("HolidayId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Milestone", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MilestoneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MilestoneId");

                    b.HasIndex("PhaseId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkTo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Phase", b =>
                {
                    b.Property<Guid>("PhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BaselineAdjustmentLog")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PlannedEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PlannedEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ProjectDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("DocumentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ProjectDocuments");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("AllocationPct")
                        .HasColumnType("float");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.RegressionItem", b =>
                {
                    b.Property<Guid>("RegressionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BugId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TestCase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VerifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("RegressionItemId");

                    b.HasIndex("BugId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("RegressionItems");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ReviewFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewFeedbacks");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ReviewSession", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReviewId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ReviewSessions");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.SupportTicket", b =>
                {
                    b.Property<Guid>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TicketCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReporterId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.SystemSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("SettingId");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DelayReasonType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("EstimateHours")
                        .HasColumnType("int");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PlannedEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssignerId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskAttachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskDependency", b =>
                {
                    b.Property<Guid>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("PredecessorTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SuccessorTaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("DependencyId");

                    b.HasIndex("PredecessorTaskId");

                    b.HasIndex("SuccessorTaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskProgressLog", b =>
                {
                    b.Property<Guid>("ProgressLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BlockerReason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DelayReasonNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DelayReasonType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("HoursLogged")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HoursOTLogged")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsOT")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PercentDone")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProgressDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("WorkContent")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("ProgressLogId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TaskProgressLogs");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TimesheetEntry", b =>
                {
                    b.Property<Guid>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConflictEventId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HoursOT")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsOT")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TimesheetId");

                    b.HasIndex("ConflictEventId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugAttachment", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.BugTicket", "BugTicket")
                        .WithMany("BugAttachments")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "UploadedByUser")
                        .WithMany("BugAttachments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BugTicket");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugRCAHistory", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.BugTicket", "BugTicket")
                        .WithMany("BugRcaHistories")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "CreatedByUser")
                        .WithMany("BugRcaHistories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BugTicket");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugTicket", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Assignee")
                        .WithMany("AssignedBugs")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Phase", "Phase")
                        .WithMany("BugTickets")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("BugTickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Reporter")
                        .WithMany("ReportedBugs")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "Task")
                        .WithMany("BugTickets")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "VerifyByUser")
                        .WithMany("VerifiedBugs")
                        .HasForeignKey("VerifyBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("Phase");

                    b.Navigation("Project");

                    b.Navigation("Reporter");

                    b.Navigation("Task");

                    b.Navigation("VerifyByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ClientContact", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Client", "Client")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ConflictEvent", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "FromProject")
                        .WithMany("ConflictEvents")
                        .HasForeignKey("FromProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "Task")
                        .WithMany("ConflictEvents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "User")
                        .WithMany("ConflictEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromProject");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Department", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Milestone", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Phase", "Phase")
                        .WithMany("Milestones")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Notification", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Phase", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("Phases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Project", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ProjectDocument", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("ProjectDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "UploadedByUser")
                        .WithMany("ProjectDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ProjectMember", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.RegressionItem", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.BugTicket", "BugTicket")
                        .WithMany("RegressionItems")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BugTicket");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ReviewFeedback", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Assignee")
                        .WithMany("ReviewFeedbacks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.ReviewSession", "ReviewSession")
                        .WithMany("ReviewFeedbacks")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ReviewSession", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Milestone", "Milestone")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Phase", "Phase")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.SupportTicket", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Assignee")
                        .WithMany("AssignedSupportTickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Phase", "Phase")
                        .WithMany("SupportTickets")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("SupportTickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Reporter")
                        .WithMany("ReportedSupportTickets")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Phase");

                    b.Navigation("Project");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Task", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "Assigner")
                        .WithMany("AssignedByTasks")
                        .HasForeignKey("AssignerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Phase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Assigner");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskAttachment", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "Task")
                        .WithMany("TaskAttachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "UploadedByUser")
                        .WithMany("TaskAttachments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskDependency", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "PredecessorTask")
                        .WithMany("PredecessorDependencies")
                        .HasForeignKey("PredecessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "SuccessorTask")
                        .WithMany("SuccessorDependencies")
                        .HasForeignKey("SuccessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredecessorTask");

                    b.Navigation("SuccessorTask");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TaskProgressLog", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "Task")
                        .WithMany("TaskProgressLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "UpdatedByUser")
                        .WithMany("TaskProgressLogs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.TimesheetEntry", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.ConflictEvent", "ConflictEvent")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("ConflictEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Task", "Task")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SME_Ecotech2A.Domain.Entity.User", "User")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConflictEvent");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.User", b =>
                {
                    b.HasOne("SME_Ecotech2A.Domain.Entity.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SME_Ecotech2A.Domain.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.BugTicket", b =>
                {
                    b.Navigation("BugAttachments");

                    b.Navigation("BugRcaHistories");

                    b.Navigation("RegressionItems");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Client", b =>
                {
                    b.Navigation("ClientContacts");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ConflictEvent", b =>
                {
                    b.Navigation("TimesheetEntries");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Milestone", b =>
                {
                    b.Navigation("ReviewSessions");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Phase", b =>
                {
                    b.Navigation("BugTickets");

                    b.Navigation("Milestones");

                    b.Navigation("ReviewSessions");

                    b.Navigation("SupportTickets");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Project", b =>
                {
                    b.Navigation("BugTickets");

                    b.Navigation("ConflictEvents");

                    b.Navigation("Phases");

                    b.Navigation("ProjectDocuments");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ReviewSessions");

                    b.Navigation("SupportTickets");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.ReviewSession", b =>
                {
                    b.Navigation("ReviewFeedbacks");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.Task", b =>
                {
                    b.Navigation("BugTickets");

                    b.Navigation("ConflictEvents");

                    b.Navigation("PredecessorDependencies");

                    b.Navigation("SuccessorDependencies");

                    b.Navigation("TaskAttachments");

                    b.Navigation("TaskProgressLogs");

                    b.Navigation("TimesheetEntries");
                });

            modelBuilder.Entity("SME_Ecotech2A.Domain.Entity.User", b =>
                {
                    b.Navigation("AssignedBugs");

                    b.Navigation("AssignedByTasks");

                    b.Navigation("AssignedSupportTickets");

                    b.Navigation("AssignedTasks");

                    b.Navigation("BugAttachments");

                    b.Navigation("BugRcaHistories");

                    b.Navigation("ConflictEvents");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedProjects");

                    b.Navigation("ProjectDocuments");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ReportedBugs");

                    b.Navigation("ReportedSupportTickets");

                    b.Navigation("ReviewFeedbacks");

                    b.Navigation("TaskAttachments");

                    b.Navigation("TaskProgressLogs");

                    b.Navigation("TimesheetEntries");

                    b.Navigation("VerifiedBugs");
                });
#pragma warning restore 612, 618
        }
    }
}
